captainVersion: 4
services:
    $$cap_appname:
        image: ghcr.io/mpo-web-consulting/wintercms:$$cap_wintercms_version
        volumes:
            - $$cap_appname-storage:/var/www/html/storage
            - $$cap_appname-themes:/var/www/html/themes
            - $$cap_appname-plugins:/var/www/html/plugins
        restart: always
        environment:
            TZ: '$$cap_TZ'
            ENABLE_CRON: 'false'
            FWD_REMOTE_IP: 'true'
            INIT_WINTER: 'true'
            LINK_POLICY: 'true'
            APP_URL: "https://$$cap_app_subdomain.$$cap_captain_root_domain"
            ASSET_URL: "https://$$cap_app_subdomain.$$cap_captain_root_domain/assets"

caproverOneClickApp:
    variables:
        - id: $$cap_TZ
          label: 'Timezone'
          defaultValue: 'Europe/Berlin'
          description: 'Setze hier deine Zeitzone (z.B. Europe/Berlin)'
        - id: $$cap_wintercms_version
          label: 'WinterCMS Version'
          defaultValue: '8.2-apache-v1.2.7-42b24fc62b77'
          description: 'Gib die WinterCMS Version ein (z.B. latest oder 8.2-apache-v1.2.7-42b24fc62b77). Hier kannst du die Versionen finden: https://github.com/mpo-web-consulting/docker-wintercms/pkgs/container/wintercms'
          validRegex: '/^([^\s^\/])+$/'
    instructions:
        start: >-
            Diese App deployt WinterCMS, eine dockerisierte Version von Winter CMS.
            Konfiguriere die benötigten Parameter und klicke auf Weiter.
        end: >-
            WinterCMS ist deployed und erreichbar als $$cap_appname.
            Wichtig: aktiviere HTTPS in der Apps Config manuell.
    displayName: WinterCMS
    isOfficial: false
    description: 'Deploye WinterCMS – eine dockerisierte Version von Winter CMS (PHP, Composer, Winter core und Abhängigkeiten).'
    documentation: 'https://github.com/MPO-Web-Consulting/docker'
